# Este archivo le dice a Netlify cómo construir y desplegar tu sitio.

[build]
  # Comando para instalar las dependencias de Python.
  command = "pip install -r requirements.txt"
  # Directorio donde se encuentran las funciones serverless (tu app de Flask).
  functions = "netlify/functions"
  # Directorio que Netlify servirá estáticamente.
  publish = "templates"

[functions]
  # Configuración específica para la función principal.
  [functions."app"]
    # Incluye la plantilla de Word en el paquete de la función
    # para que el script de Python pueda encontrarla.
    included_files = ["plantilla_informe.docx"]

# --- NUEVA REGLA DE REDIRECCIÓN ---
# Esto le dice a Netlify que cualquier petición a "/generar"
# debe ser manejada por la función 'app' en su ruta '/generar'.
[[redirects]]
  from = "/generar"
  to = "/.netlify/functions/app/generar"
  status = 200 # Un status 200 lo convierte en una reescritura (rewrite) en lugar de una redirección.

